# Generated by Django 5.0.6 on 2024-05-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('management_category', models.CharField(max_length=100)),
                ('network_category', models.CharField(max_length=100)),
                ('group_user', models.CharField(max_length=100)),
                ('group_owner', models.CharField(max_length=100)),
                ('responsible_employee', models.CharField(max_length=100)),
                ('physical_location', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('sub_service', models.CharField(max_length=100)),
                ('access_type', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('unpatchable', models.CharField(max_length=100)),
                ('ref_num', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('siem_log', models.CharField(max_length=300)),
            ],
        ),
    ]
